language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - memcached
  - redis-server

install:
   - composer install

script:
    - ./bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
