Cache:
  adapter:
    local:
      type: Filesystem
      path: '/tmp'
    memcached:
      type: Memcached
      servers:
        memcached1: { host: localhost, port: 11211 }
    redis:
      type: Predis
      servers:
        redis1: { host: localhost, port: 6379 }
